# Generated by Django 5.2.7 on 2026-02-18 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_hours_limit',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Horas de estudio configuradas para planificar tareas (1-16).', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(24.0)], verbose_name='límite de horas diarias'),
        ),
    ]
