# Generated by Django 5.2.7 on 2026-02-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('EXAMEN', 'examen'), ('QUIZ', 'quiz'), ('TALLER', 'taller'), ('PROYECTO', 'proyecto'), ('OTRO', 'otro')], default='TALLER', max_length=10),
        ),
    ]
