# Generated by Django 5.2.7 on 2026-02-27 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_activity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('examen', 'Examen'), ('quiz', 'Quiz'), ('taller', 'Taller'), ('proyecto', 'Proyecto'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'user')},
        ),
    ]
