# Generated by Django 5.2.7 on 2026-03-21 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_activity_type_alter_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosponedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posponed_logs', to='planner.subtask')),
            ],
        ),
    ]
