# Generated by Django 5.2.7 on 2026-03-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_posponedlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='execution_note',
        ),
    ]
